CC = gcc

all:
	$(CC) -o server1.out server.c -lpthread -lrt
	$(CC) -o server2.out server2.c -lpthread -lrt
	$(CC) -o server3.out server3.c -lpthread -lrt

server1:
	$(CC) -o server1.out server.c -lpthread -lrt

server2:
	$(CC) -o server2.out server2.c -lpthread -lrt

server3:
	$(CC) -o server3.out server3.c -lpthread -lrt